### 
//resigter
POST http://localhost:5000/api/users/register 
Content-Type: application/json


{
	"name":"crazy1",
	"email":"crazy1@gmail.com",
	"password":"Crazy1@1207"
}
	 
### 
//login
POST http://localhost:5000/api/users/login
Content-Type: application/json


{
	"email":"crazy1@gmail.com",
	"password":"Crazy1@1207"
}

### 
//find user
GET http://localhost:5000/api/users/find/670aaf460394040fb7b3e49d


### 
//find user
GET http://localhost:5000/api/users

###
//create chat
POST http://localhost:5000/api/chats
Content-Type: application/json

{
  "firstId": "670aaf460394040fb7b3e49d",
  "secondId": "670aaf150394040fb7b3e49a"
}

###
//find user chats 
GET http://localhost:5000/api/chats/670aaf150394040fb7b3e49a

###
//find chat
GET http://localhost:5000/api/chats/find/670aaf460394040fb7b3e49d/670aaf150394040fb7b3e49a


###
//send message
POST http://localhost:5000/api/messages
Content-Type: application/json

{
	"chatId": "670ca372d83d8cfed4e1ee6f",
	"senderId":"670aaf460394040fb7b3e49d",
	"text":"hello Crazy"
}

###
//find messages
GET http://localhost:5000/api/messages/670ca372d83d8cfed4e1ee6f
