### 
//resigter
POST http://localhost:5000/api/users/register 
Content-Type: application/json


{
	"name":"crazy1",
	"email":"crazy1@gmail.com",
	"password":"Crazy@1207"
}
	 
### 
//login
POST http://localhost:5000/api/users/login
Content-Type: application/json


{
	"email":"crazy1@gmail.com",
	"password":"Crazy@1207"
}

### 
//find user
GET http://localhost:5000/api/users/find/66eea9e1bf0d5f5018e03772


### 
//find user
GET http://localhost:5000/api/users

###
//create chat
POST http://localhost:5000/api/chats

Content-Type: application/json

{
	"firstId": "66f40f5f01b24575cf789b87",
	"secondId":"66f4127f3c2e26684db33c18"
}

###
//find user chats 

GET http://localhost:5000/api/chats/66f40f5f01b24575cf789b87

###
//find chat

GET http://localhost:5000/api/chats/find/66f40f5f01b24575cf789b87/66f4127f3c2e26684db33c18


###
//send message

POST http://localhost:5000/api/messages
Content-Type: application/json

{
	"chatId": "67092f10a8bfedca56473a56",
	"senderId":"66f40f5f01b24575cf789b87",
	"text":"hello"
}

###
//find messages
GET http://localhost:5000/api/messages/67092f10a8bfedca56473a56
